name: engtpscanner



publish_to: 'none'



flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/













version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'







dependencies:

  flutter:
    sdk: flutter
  get: ^4.6.6
  path: any
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  flutter_barcode_scanner: ^2.0.0
  pdf: any


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter





flutter_native_splash  :
  color: "#FFFFFF"
  image : assets/logo/scanner.png



  android_13 :
    icon_background_color: "#FFFFFF"
    image : assets/logo/scanner.png